name = "StagDiDModels"
uuid = "f3ca54ac-a19f-4bec-bcb5-33c111799ce9"
authors = ["Elias Ohneberg <elias.ohneberg@gmail.com>"]
version = "0.1.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CovarianceMatrices = "60f91f6f-d783-54cb-84f9-544141854719"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

 
[extensions]
StagDiDModelsMakieExt = "Makie"

[compat]
CSV = "0.10.15"
CairoMakie = "0.15.8"
CategoricalArrays = "1.0.1"
CovarianceMatrices = "0.22.0"
DataFrames = "1.7.0"
Distributions = "0.25.120"
FixedEffectModels = "1.12.0"
LinearAlgebra = "1.11.0"
Logging = "1.11.0"
Makie = "0.24.8"
Printf = "1.11.0"
Random = "1.11.0"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
StatsAPI = "1.7.1"
StatsBase = "0.34.6"
StatsFuns = "1.5.0"
StatsModels = "0.7.5"
